services:
  - type: web
    name: forecastai
    env: node
    buildCommand: npm install && npm run build:prod
    startCommand: cd dist && npm install && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
