services:
  - type: web
    name: forecastai
    env: node
    buildCommand: npm install && pip install -r requirements.txt && npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://foodforecastai.netlify.app
      - key: PYTHON_PATH
        value: python3
      - key: TIMEGPT_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: VITE_AWS_ACCESS_KEY_ID
        sync: false
      - key: VITE_AWS_SECRET_ACCESS_KEY
        sync: false
      - key: VITE_AWS_REGION
        value: us-east-2
      - key: VITE_S3_BUCKET_NAME
        sync: false
      - key: VITE_DB_HOST
        sync: false
      - key: VITE_DB_NAME
        sync: false
      - key: VITE_DB_USER
        sync: false
      - key: VITE_DB_PASSWORD
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
